### PR TITLE
Fixed some things!

### PR DESCRIPTION
**Pull request by ItzKoolKid96**

### CODE REVIEW

**Comment by devnote-dev** [comment]
You have merge conflicts; please resolve them.

**Comment by ItzKoolKid96** [comment]
This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files
Dasgactyl-Corona-Theme-Theme-v1/README.md

**Comment by devnote-dev** [comment]
I'm aware, you need to resolve it on your end.

**Comment by ItzKoolKid96** [comment]
i cant do that the button dose not show! Jamie needs to merge this!

**Pull request closed without merging**
